language: python

sudo: false

cache: pip

matrix:
  include:
    - python: 2.6
      env: TOXENV=py26
    - python: 2.7
      env: TOXENV=py27
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: pypy
      env: TOXENV=pypy

install:
    - pip install --install-option="--no-cython-compile" https://github.com/cython/cython/archive/557fd54ae9308a087993ebc66be0c58bf7f33040.zip
    - pip install tox

script: tox
