language: python

sudo: false

cache: pip

matrix:
  include:
    - python: 2.6
      env: TOXENV=py26
    - python: 2.7
      env: TOXENV=py27
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: pypy
      env: TOXENV=pypy

install:
    - pip install --install-option="--no-cython-compile" https://github.com/cython/cython/archive/3134ec551ae09b880d71999f16f035683b47a8dc.zip
    - pip install tox

script: tox
